/* splitinfer/runtime/tests/test_gpu_executor.cpp
 *
 * Hardware integration test for the TensorRT-backed GpuExecutor.
 *
 * Validates that:
 *   1. A pre-built TensorRT engine file can be loaded via GpuExecutor::load_engine()
 *   2. GpuExecutor::execute() correctly runs the engine on real GPU hardware
 *   3. The output for a known input matches the expected result
 *
 * The test uses a tiny "identity matmul" engine (y = x @ I where I is the
 * 4x4 identity matrix), so the expected output is bit-exactly the input.
 * This avoids floating-point comparison fuzz and gives us a binary
 * "did the GPU run my model?" answer.
 *
 * Build (only when SPLITINFER_HAS_TENSORRT=ON):
 *   cmake .. -DBUILD_TESTS=ON -DSPLITINFER_HAS_TENSORRT=ON
 *   make test_gpu_executor
 *
 * Run:
 *   ./runtime/test_gpu_executor [path_to_identity.engine]
 *
 * The default engine path is /tmp/trt_test/identity.engine, generated by:
 *   /usr/src/tensorrt/bin/trtexec --onnx=identity.onnx --saveEngine=identity.engine
 */

#include "splitinfer/gpu_executor.h"

#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string>
#include <vector>

#ifndef SPLITINFER_HAS_TENSORRT
int main(void) {
    std::fprintf(stderr,
        "test_gpu_executor: built without SPLITINFER_HAS_TENSORRT — skipping.\n"
        "  Reconfigure with -DSPLITINFER_HAS_TENSORRT=ON to enable this test.\n");
    return 77; /* 77 = SKIP per autoconf convention */
}
#else

/* Compare two FP32 vectors with a small tolerance.  Returns true if all
 * elements match within `tol` absolute difference. */
static bool fp32_vec_equal(const float* a, const float* b, size_t n, float tol) {
    for (size_t i = 0; i < n; ++i) {
        float diff = std::fabs(a[i] - b[i]);
        if (diff > tol) {
            std::fprintf(stderr,
                "  Mismatch at index %zu: got %.6f, expected %.6f (diff %.6f)\n",
                i, a[i], b[i], diff);
            return false;
        }
    }
    return true;
}

int main(int argc, char* argv[]) {
    const char* engine_path = (argc > 1) ? argv[1] : "/tmp/trt_test/identity.engine";

    std::printf("=== GpuExecutor TensorRT Hardware Integration Test ===\n");
    std::printf("Engine: %s\n\n", engine_path);

    splitinfer::GpuExecutor gpu;

    /* ── Step 1: Load the pre-built engine ──────────────────────────────── */
    std::printf("[1/3] Loading TensorRT engine ... ");
    std::fflush(stdout);
    if (!gpu.load_engine("identity_matmul", engine_path)) {
        std::printf("FAIL\n");
        std::fprintf(stderr,
            "  Could not load engine.  Build it first with:\n"
            "    /usr/src/tensorrt/bin/trtexec --onnx=identity.onnx \\\n"
            "        --saveEngine=%s\n", engine_path);
        return 1;
    }
    std::printf("OK\n");

    /* ── Step 2: Run inference with a known input pattern ───────────────── */
    std::printf("[2/3] Running inference on real GPU ... ");
    std::fflush(stdout);

    /* Input: 4 distinct floats so we can detect any reordering bugs. */
    const float input[4]    = { 1.0f, 2.0f, 3.0f, 4.0f };
    const float expected[4] = { 1.0f, 2.0f, 3.0f, 4.0f };  /* y = x @ I = x */

    float output[4] = { 0, 0, 0, 0 };
    bool ok = gpu.execute("identity_matmul",
                          input,  sizeof(input),
                          output, sizeof(output));
    if (!ok) {
        std::printf("FAIL (executor returned false)\n");
        return 2;
    }
    std::printf("OK\n");

    /* ── Step 3: Verify output matches input (identity matmul) ──────────── */
    std::printf("[3/3] Verifying output ... ");
    std::fflush(stdout);

    if (!fp32_vec_equal(output, expected, 4, /*tol=*/1e-6f)) {
        std::printf("FAIL (output mismatch)\n");
        std::fprintf(stderr, "  input    = [%.3f, %.3f, %.3f, %.3f]\n",
                     input[0], input[1], input[2], input[3]);
        std::fprintf(stderr, "  output   = [%.3f, %.3f, %.3f, %.3f]\n",
                     output[0], output[1], output[2], output[3]);
        std::fprintf(stderr, "  expected = [%.3f, %.3f, %.3f, %.3f]\n",
                     expected[0], expected[1], expected[2], expected[3]);
        return 3;
    }
    std::printf("OK\n");
    std::printf("  input    = [%.3f, %.3f, %.3f, %.3f]\n",
                input[0], input[1], input[2], input[3]);
    std::printf("  output   = [%.3f, %.3f, %.3f, %.3f]\n",
                output[0], output[1], output[2], output[3]);

    /* ── Step 4 (bonus): Run a second input to confirm engine reusability ─ */
    std::printf("\n[bonus] Re-running with different input ... ");
    std::fflush(stdout);
    const float input2[4]    = { -0.5f, 100.0f, 0.0f, 3.14159f };
    const float expected2[4] = { -0.5f, 100.0f, 0.0f, 3.14159f };
    float output2[4] = { 0, 0, 0, 0 };
    ok = gpu.execute("identity_matmul",
                     input2,  sizeof(input2),
                     output2, sizeof(output2));
    if (!ok || !fp32_vec_equal(output2, expected2, 4, 1e-5f)) {
        std::printf("FAIL\n");
        return 4;
    }
    std::printf("OK\n");
    std::printf("  input    = [%.3f, %.3f, %.3f, %.3f]\n",
                input2[0], input2[1], input2[2], input2[3]);
    std::printf("  output   = [%.3f, %.3f, %.3f, %.3f]\n",
                output2[0], output2[1], output2[2], output2[3]);

    std::printf("\n=== ALL TESTS PASSED ===\n");
    return 0;
}

#endif /* SPLITINFER_HAS_TENSORRT */
